### ISSUE TITLE
Frame id must start with "/".

### ISSUE THREAD

**Issue by blmhemu** [ros-drivers/nmea_navsat_driver#39] opened 2017-12-10 17:14 UTC
This is changed in the latest tf2 release. It gives warning when a slash is present.

**Comment by evenator** [comment] 2017-12-15 16:20
There was some discussion about this previously in #35, but it sounds like there's now a deprecation warning. I'm hesitant to change the behavior in existing releases for the reason that @jack-oquin stated in that discussion--I suspect some users are expecting the leading slash. I'd like to hear what others think about this. I think the best course of action is probably to make this change in lunar only.

**Comment by evenator** [comment] 2017-12-15 16:20
See also #40

**Comment by evenator** [comment] 2017-12-15 16:25
After looking through the issues and PRs here, I'm closing this as a duplicate of #24. Please continue all discussion there.

**Closed by evenator** 2017-12-15 16:25 UTC
