### ISSUE TITLE
frame_id include a "/" which cannot work in tf2

### ISSUE THREAD

**Issue by roccogalati** [ros-drivers/nmea_navsat_driver#31] opened 2017-03-21 11:52 UTC
Hello guys,

I'm having problems with the `nmea_navsat_driver` under Indigo since it publishes a frame_id as /gps which includes a backslash which is not allowed in `tf2` standard.
I tried to launch the driver with the " `_frame_id:=gps`" parameter but it still continues to add the backslash to the frame name. 
Is it possible to change this, please? I cannot correctly run my ROS codes since I always get this error:
` Could not obtain transform from /gps to base_link. Error was Invalid argument "/gps" passed to lookupTransform argument source_frame in tf2 frame_ids cannot start with a '/' like: `

Thank you!

**Comment by jack-oquin** [comment] 2017-03-23 17:34
That does look like a bug.

If you submit a pull request with a fix for it, you're likely to get it done sooner. (I am not the maintainer of this package.)

**Comment by evenator** [comment] 2017-12-15 16:24
This is a duplicate of #24

**Closed by evenator** 2017-12-15 16:24 UTC
